### ISSUE TITLE
Respect project exclude_patterns

### ISSUE THREAD

**Issue by imccowan** [csch0/SublimeText-File-Navigator#3]
Sublime File Navigator renders Sublime Text 2 (build 2181) unresponsive on Windows when I use it in a project with a folder with a lot of very full subdirectories, even though I have all those folders excluded from the project in the sidebar.  I see that Sublime File Navigator has its own excluded_dir_patterns setting, but I think it should use the current project's folder_exclude_patterns in addition.

**Comment by imccowan** [comment]
In trying to implement this myself, I see that it's pretty hairy because of the lack of an API for project settings. It looks like it could be done by swiping some code from SideBarEnhancements (see getProjectJson in https://github.com/titoBouzout/SideBarEnhancements/blob/master/sidebar/SideBarProject.py) but maybe you just want to wait for a proper project API, I don't know.

**Comment by belike81** [comment]
You're right. I'll update the plugin during the weekend.
