### ISSUE TITLE
"Open in Explorer"

### ISSUE THREAD

**Issue by samholmes** [csch0/SublimeText-File-Navigator#4]
I'm suggesting an option to open a directory or file in an Explorer window (or Finder window for OS X). Also, a "Show in Explorer" option for individual files would be appropriate as well.

**Comment by samholmes** [comment]
No comment? Why did you close the issue if it hasn't been resolved?

**Comment by csch0** [comment]
Just took over the plugin and rewrote it from scratch, will eventual look into this feature. Added to my notes, sorry for not leaving a note.

**Comment by csch0** [comment]
This is now included!
